syntax = "proto3";
package geoscribefs;

service GeoScribeFsService {
  rpc Status(StatusRequest) returns (StatusResponse);
  rpc Write(WriteRequest) returns (WriteResponse);
  rpc AskWrite(AskWriteRequest) returns (AskWriteResponse);
  rpc Snapshot(SnapshotRequest) returns (SnapshotResponse);
  rpc Restore(RestoreRequest) returns (RestoreResponse);
}

message StatusRequest {}

message StatusResponse {
  string status = 1;
}

message WriteRequest {
  string volume_name = 1;
}

message WriteResponse {
  bool success = 1;
}

message AskWriteRequest {
  string volume_name = 1;
}

message AskWriteResponse {
  bool can_write = 1;
}

message SnapshotRequest {
  string volume_name = 1;
}

message SnapshotResponse {
  bool success = 1;
  string date = 2;
}

message RestoreRequest {
  string volume_name = 1;
  string date = 2;
}

message RestoreResponse {
  bool success = 1;
}
